package scanner;

/**
 * Enumeration of possible {@link Symbol} types.
 */
public enum SymbolType {
    CLASS, CURLY_BRACE_OPEN, CURLY_BRACE_CLOSE, FINAL, EQUALS, SEMICOLON, PUBLIC, VOID, PARENTHESES_OPEN,
    PARENTHESIS_CLOSE, COMMA, INT, IF, ELSE, WHILE, RETURN, EQUALS_EQUALS, LESS_THAN, LESS_THAN_EQUALS,
    GREATER_THAN, GREATER_THAN_EQUALS, PLUS, MINUS, TIMES, SLASH, COMMENT_START, COMMENT_STOP, IDENT, NUMBER, EOF
}